CREATE TABLE SESSIONS
(
    ID          SERIAL PRIMARY KEY,
    HALL_ID     INTEGER REFERENCES HALLS (ID),
    DATA_START  TIMESTAMP NOT NULL,
    MOVIE_TITLE TEXT NOT NULL
);
GO
INSERT INTO SESSIONS (HALL_ID, DATA_START, MOVIE_TITLE)
VALUES (1, '2021-01-23 10:20:00', 'The Best Movie 0+');