CREATE TABLE HALLS
(
    ID               SERIAL PRIMARY KEY,
    TITLE            TEXT,
    NUMBER_OF_PLACES INTEGER NOT NULL,
    NUMBER_OF_ROWS   INTEGER NOT NULL,
    CAPACITY         INTEGER NOT NULL
);
GO
INSERT INTO HALLS (TITLE, NUMBER_OF_PLACES, NUMBER_OF_ROWS, CAPACITY) VALUES ('Green', 9, 5, 45);