CREATE TABLE TICKETS
(
    ID           SERIAL PRIMARY KEY,
    DATA_OF_SALE TIMESTAMP NOT NULL,
    SESSION_ID   INTEGER REFERENCES SESSIONS (ID),
    ROW          INTEGER   NOT NULL,
    PLACE        INTEGER   NOT NULL,
    PRICE        INTEGER   NOT NULL,
    STATUS       TEXT      NOT NULL,
    NAME_USER    TEXT      NOT NULL,
    PHONE_USER   TEXT      NOT NULL,
    CONSTRAINT uniquePlace UNIQUE (SESSION_ID, ROW, PLACE)
);
GO
INSERT INTO TICKETS (DATA_OF_SALE, SESSION_ID, ROW, PLACE, PRICE,STATUS, NAME_USER, PHONE_USER)
VALUES ('2021-01-19 15:23:46', 1, 2, 4, 200, 'Sold', 'User One', '81234567890');
GO
INSERT INTO TICKETS (DATA_OF_SALE, SESSION_ID, ROW, PLACE, PRICE,STATUS, NAME_USER, PHONE_USER)
VALUES ('2021-01-19 12:23:46', 1, 3, 5, 200, 'Sold', 'User Two', '81234567890');